# Generated by Django 5.0 on 2024-05-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='img',
            field=models.ImageField(default='media/arlacchino_badass_edit-Cover_RlOWyJ1.jpg', null=True, upload_to='profile-image/'),
        ),
        migrations.DeleteModel(
            name='Pricing',
        ),
    ]
