# Generated by Django 5.0 on 2024-05-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_alter_user_reg_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='img',
            field=models.ImageField(default='../static/assets/images/logo.svg', null=True, upload_to='profile-image/'),
        ),
    ]
