# Generated by Django 5.0 on 2024-05-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_alter_user_reg_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_reg',
            name='img',
        ),
    ]
