# Generated by Django 5.0 on 2024-05-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_remove_user_reg_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='img',
            field=models.ImageField(null=True, upload_to='profile-image/'),
        ),
    ]
