# Generated by Django 5.0 on 2024-05-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0009_remove_feedback_user_id_remove_contact_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='movie_quality',
        ),
    ]
