# Generated by Django 5.0 on 2024-05-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0010_remove_addproduct_movie_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
