# Generated by Django 5.0 on 2024-05-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0011_addproduct_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
